name: Generate issue

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  generate-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout repository
        uses: actions/checkout@v4

      - name: Generate issue
        uses: aegisfleet/gemini-generate-issue@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gemini-token: ${{ secrets.GEMINI_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
